name: NovaUtils
author: snowbud56
version: 1.0
main: com.snowbud56.NovaUtils
api-version: 1.13
commands:
  skin:
    description: Changes your skin to whatever you set.
  rtp:
    description: Random teleportation! :)
  sc:
    description: What's this?